### ISSUE TITLE
Add a Dictionary Builder

### ISSUE THREAD

**Issue by panathea** [Germanika/plover#21]
1. Select text to read from.
2. Option: exclude words already in dictionary (default checked)
3. Define strokes for word n
    3a. **Translation** field is editable and will "stick"
    3b. **Dictionary** field is editable and will "stick"
    3c. Add stroke and define again
    3d. Add stroke and go to next word (n+1)
    3e. Go to next word without defining stroke
    3f. Undo: undoes last added stroke and puts you into right before it was added (so strokes are filled out)
    3g. Quit

Regex will:
  - be case sensitive (prone to words at the beginning of sentences, but shouldn't matter with a large enough sample text)
  - ignore punctuation, except `-` and `'`
  - handle accented characters

I worry whether a comma-separated list of emoji would work well or not. We'll see?

**Comment by panathea** [comment]
Some additional thoughts!
- **Word Order**
  - Frequency (descending)
  - Alphabetical (ascending)
  - Order of Appearance (first unique appearance)
- There should be a hint that shows way to stroke the current word, especially as you start adding a few; you want to see what you just defined to not waste time.

**Comment by panathea** [comment]
@Germanika @sofa13 wanna review my mockup? https://xd.adobe.com/view/0ed686d3-3237-489e-b037-252932fb1c35/

**Comment by panathea** [comment]
Fun thought, instead of just searching for words, we should support words in the form `\b{.*}\b` which would let users add a list of commands, like the list of commands that will be necessary to be functional in the dictionary builder:
- `{#tab}` tab between boxes
- `{#shift(tab)}` tab backwards between boxes
- `{#return}{^}` add
- `{#control(return)}{^}` or `{#command(return)}{^}` add and go to next word
- `{#control(z)}{^}` or `{#command(z)}{^}` undo
- `{#control(w)}` quit
- `{#control(t)}` skip?

**Comment by iangermann** [comment]
I'm not sure about the use case of adding commands through the dictionary builder. I thought the main idea was to scan for domain-specific words you don't know about yet. Commands are basically always going to be user-defined so they could just as easily be added through creating/editing a dictionary, no?

**Comment by iangermann** [comment]
The mockup looks really good! Some thoughts:  
- I don't think it's necessary to have separate "Add" and "Add and Next" actions as I suspect "Add and Next" will almost always be the action you want to take anyway.  
- Is there a way to define multiple entries for the given translation? (I just realized this might be what "Add" does..
- Do you plan to support finding common phrases as well as words? This would add a bit of complexity, but I think might be useful in the future

**Comment by panathea** [comment]
There are two major use cases for building. One, adding an article of text
and pulling out domain specific words. Two, a list of words. E.g. Pokemon.
Or, you might use it to review what is already in your dictionary for a
list of words, names, or in this case, commands.

It would be nice to be able to provide a list of suffixes and let people
flow through them and define strokes or compare with what's in their
dictionary. E.g. {in^} {pre^} {un^} {out^} etc. it's a different sort of
word list but I think it would be useful for the plover community in
general.

**Comment by sofa13** [comment]
Yeah looks good ted! 
Couple thoughts I'll mention:
- When first starting to build dictionary, you ask the user to paste text in the box, should we also give the user the option of choosing a text file vs pasting the text? Or would this prove too difficult with different text formattings?
- Should there be some kind of "Save and Quit" as well as "Quit" ? Cause as a user i can think of scenarios where I'd change my mind about building a dictionary, and I'd want to quit as if I had done nothing vs. quit and save what I built.

**Comment by panathea** [comment]
Nah, there's no quit without saving because all changes are live. It would be a significant effort to implement so at the very least I'm not willing to yet.

For the beginning option...file selection isn't a bad idea. But pasting is nice because everyone can do it from any format. Wouldn't want someone trying to open a word file or a webpage when they are not supported. Pasting I think is a good start.

**Comment by sofa13** [comment]
Yeah fair enough, your mockup ideas seem to be a good way to start things off then.

**Comment by panathea** [comment]
Hm, phrases are a good point I hadn't considered as well.

**Comment by panathea** [comment]
Aight some feedback from Mirabai:

- Remove pure numbers (but `free2play` would be fine, while `1234` wouldn't.)
- Add option to remove entries from list before in add mode? Would need some design.
