### ISSUE TITLE
Add option to create new dictionary

### ISSUE THREAD

**Issue by iangermann** [Germanika/plover#24]
There's currently no way to create a new blank dictionary

**Comment by panathea** [comment]
Sad

**Comment by iangermann** [comment]
@morinted any thoughts on an icon for this? The "+" icon is already being used for adding an existing dictionary to the list

**Comment by panathea** [comment]
For now I'd just use the generic "new page" icon, I can fix that later. https://commons.wikimedia.org/wiki/GNOME_Desktop_icons#/media/File:Gnome-document-new.svg
