### ISSUE TITLE
Sign up for Hacktober Fest

### ISSUE THREAD

**Issue by panathea** [Germanika/plover#5]
- [x] @Germanika 
- [x] @sofa13 
- [x] @edalp008
- [x] @morinted

https://hacktoberfest.digitalocean.com/sign_up/register

Submit 4 pull requests in the month of October and get a free T-shirt to celebrate. Pretty cool and it will give incentive to PR in the upcoming month!

**Comment by sofa13** [comment]
Free T-shirts?!? I'm in!

**Comment by edalp008** [comment]
Registereeddddd

**Comment by panathea** [comment]
@Germanika We are pending on response from you 👿

**Comment by iangermann** [comment]
Done!
